// scripts/envBootstrap.js
import process from "process";

/* ============================================================
   Helpers
============================================================ */
const req = (k) => {
  const v = process.env[k];
  if (v === undefined || String(v).trim() === "") {
    throw new Error(`Missing env: ${k}`);
  }
  return v;
};

const opt = (k, d = undefined) => {
  const v = process.env[k];
  return v === undefined ? d : v;
};

const str = (k, d = undefined) => {
  const raw = opt(k, d);
  if (raw === undefined || raw === null) return raw;
  return String(raw).trim();
};

const firstDefined = (...keys) => {
  for (const key of keys) {
    if (process.env[key] !== undefined && String(process.env[key]).trim() !== "") {
      return String(process.env[key]).trim();
    }
  }
  return undefined;
};

const num = (k, d = undefined) => {
  const raw = opt(k, d);
  if (raw === undefined) return undefined;
  const n = Number(raw);
  if (Number.isNaN(n)) {
    throw new Error(`Env ${k} must be numeric (got "${raw}")`);
  }
  return n;
};

const bool = (k, d = undefined) => {
  const raw = opt(k, d);
  if (raw === undefined) return undefined;
  return ["1", "true", "yes", "on", "y"].includes(
    String(raw).toLowerCase()
  );
};

/* ============================================================
   ENV (Authoritative Contract)
============================================================ */
export const ENV = {
  /* ---------------- Core ---------------- */
  NODE_ENV: str("NODE_ENV", "development").toLowerCase(),
  PORT: num("PORT", 3000),
  LOG_LEVEL: str("LOG_LEVEL", "info"),
  NODE_OPTIONS: str("NODE_OPTIONS"),
  APP_TITLE: str("APP_TITLE"),
  APP_URL: str("APP_URL"),
  SITE_BASE_URL: str("SITE_BASE_URL"),

  DEBUG_ROUTES: bool("DEBUG_ROUTES", false),
  AUTO_CALL: opt("AUTO_CALL", "yes"),

  JSON_BODY_LIMIT: opt("JSON_BODY_LIMIT", "10mb"),
  URLENCODED_BODY_LIMIT: opt("URLENCODED_BODY_LIMIT", "10mb"),
  CORS_ORIGINS: opt("CORS_ORIGINS"),
  TRUST_PROXY: opt("TRUST_PROXY"),
  SHUTDOWN_TIMEOUT_MS: num("SHUTDOWN_TIMEOUT_MS", 10000),
  SERVER_LISTEN_TIMEOUT_MS: num("SERVER_LISTEN_TIMEOUT_MS"),
  BOOTSTRAP_STEP_TIMEOUT_MS: num("BOOTSTRAP_STEP_TIMEOUT_MS", 120000),
  STARTUP_CHECK_REQUIRED_POST_START: bool("STARTUP_CHECK_REQUIRED_POST_START", false),
  EXIT_ON_REQUIRED_POST_START_FAILURE: bool("EXIT_ON_REQUIRED_POST_START_FAILURE"),
  STARTUP_CHECK_SCRIPT: opt("STARTUP_CHECK_SCRIPT"),

  /* ---------------- Suite auth / state ---------------- */
  AIMS_API_KEY: opt("AIMS_API_KEY"),
  RMS_API_KEY: opt("RMS_API_KEY"),
  WEB_API_KEY: opt("WEB_API_KEY"),
  AI_SUITE_API_KEY: opt("AI_SUITE_API_KEY"),
  AI_SUITE_AUDIT_CALLBACK_TOKEN: opt("AI_SUITE_AUDIT_CALLBACK_TOKEN"),
  AIMS_ALLOW_UNAUTHENTICATED_DEV: bool("AIMS_ALLOW_UNAUTHENTICATED_DEV", false),

  APP_TMP_DIR: opt("APP_TMP_DIR"),
  APP_STATE_DIR: opt("APP_STATE_DIR"),
  STATE_BACKEND: opt("STATE_BACKEND", "auto"),
  STATE_REMOTE_PREFIX: opt("STATE_REMOTE_PREFIX", "state"),
  ALLOW_EPHEMERAL_STATE: bool("ALLOW_EPHEMERAL_STATE", false),
  REQUIRE_DURABLE_STATE: bool("REQUIRE_DURABLE_STATE"),
  JOB_STATUS_TTL_MS: num("JOB_STATUS_TTL_MS", 86400000),
  HOOKDECK_DEDUPE_TTL_MS: num("HOOKDECK_DEDUPE_TTL_MS", 21600000),
  INTERNAL_BASE_HOST: opt("INTERNAL_BASE_HOST", "127.0.0.1"),
  INTERNAL_BASE_PROTO: opt("INTERNAL_BASE_PROTO", "http"),
  INTERNAL_ROUTE_TIMEOUT_MS: num("INTERNAL_ROUTE_TIMEOUT_MS", 60000),
  WEBHOOK_TIMEOUT_MS: num("WEBHOOK_TIMEOUT_MS"),

  RATE_LIMIT_ENABLED: bool("RATE_LIMIT_ENABLED", true),
  RATE_LIMIT_WINDOW_MS: num("RATE_LIMIT_WINDOW_MS", 60000),
  RATE_LIMIT_MAX_REQUESTS: num("RATE_LIMIT_MAX_REQUESTS", 60),

  /* ---------------- AI runtime ---------------- */
  AI_MAX_RETRIES: num("AI_MAX_RETRIES", 1),
  AI_MAX_TOKENS: num("AI_MAX_TOKENS", 4096),
  AI_RETRY_BASE_MS: num("AI_RETRY_BASE_MS", 750),
  AI_TEMPERATURE: num("AI_TEMPERATURE", 0.65),
  AI_TIMEOUT: num("AI_TIMEOUT", 90000),
  AI_TOP_P: num("AI_TOP_P", 0.9),
  AI_USAGE_LOG_ENABLED: bool("AI_USAGE_LOG_ENABLED", true),

  AI_MODEL_FAST: opt("AI_MODEL_FAST"),
  AI_MODEL_STANDARD: opt("AI_MODEL_STANDARD"),
  AI_MODEL_HIGH_QUALITY: opt("AI_MODEL_HIGH_QUALITY"),
  AI_MODEL_FALLBACK: opt("AI_MODEL_FALLBACK"),
  AI_MODEL_JSON: opt("AI_MODEL_JSON"),
  AI_MODEL_SUMMARY: opt("AI_MODEL_SUMMARY"),
  AI_MODEL_AUDIT: opt("AI_MODEL_AUDIT"),
  AI_MODEL_IMAGE: opt("AI_MODEL_IMAGE"),

  /* ---------------- Audit controls ---------------- */
  AUDIT_AI_MAX_RETRIES: num("AUDIT_AI_MAX_RETRIES", 0),
  AUDIT_AI_MAX_TOKENS: num("AUDIT_AI_MAX_TOKENS", 9000),
  AUDIT_AI_RETRY_BASE_MS: num("AUDIT_AI_RETRY_BASE_MS", 500),
  AUDIT_AI_TEMPERATURE: num("AUDIT_AI_TEMPERATURE", 0.15),
  AUDIT_AI_TIMEOUT_MS: num("AUDIT_AI_TIMEOUT_MS", 240000),
  AUDIT_AI_TOP_P: num("AUDIT_AI_TOP_P", 0.95),
  AUDIT_ANALYSIS_MAX_WAIT_SECONDS: num("AUDIT_ANALYSIS_MAX_WAIT_SECONDS", 900),
  AUDIT_CALLBACK_TOKEN: opt("AUDIT_CALLBACK_TOKEN"),
  AUDIT_CALLBACK_BASE_URL: opt("AUDIT_CALLBACK_BASE_URL"),
  AUDIT_RUN_REUSE_ACTIVE_MS: num("AUDIT_RUN_REUSE_ACTIVE_MS"),
  AUDIT_WEBSITE_REPO_OWNER: opt("AUDIT_WEBSITE_REPO_OWNER"),
  AUDIT_WEBSITE_REPO_NAME: opt("AUDIT_WEBSITE_REPO_NAME"),
  AUDIT_WEBSITE_REPO_REF: opt("AUDIT_WEBSITE_REPO_REF", "main"),
  GITHUB_TOKEN_WEBSITE_AUDITS: opt("GITHUB_TOKEN_WEBSITE_AUDITS"),
  ON_BRAND_AUDIT_MAX_TOKENS: num("ON_BRAND_AUDIT_MAX_TOKENS"),
  ON_BRAND_AUDIT_TEMPERATURE: num("ON_BRAND_AUDIT_TEMPERATURE"),
  ON_BRAND_AUDIT_TIMEOUT_MS: num("ON_BRAND_AUDIT_TIMEOUT_MS"),

  /* ---------------- OpenRouter ---------------- */
  OPENROUTER_API_BASE: str("OPENROUTER_API_BASE"),
  OPENROUTER_BASE_URL: str("OPENROUTER_BASE_URL"),
  OPENROUTER_API_KEY: opt("OPENROUTER_API_KEY"),
  OPENROUTER_SITE_URL: opt("OPENROUTER_SITE_URL"),
  OPENROUTER_APP_NAME: opt("OPENROUTER_APP_NAME"),
  OPENROUTER_SORT_BY: opt("OPENROUTER_SORT_BY"),
  OPENROUTER_SERVICE_TIER: opt("OPENROUTER_SERVICE_TIER"),
  OPENROUTER_ENABLE_FALLBACKS: bool("OPENROUTER_ENABLE_FALLBACKS"),
  OPENROUTER_REQUIRE_PARAMETERS: bool("OPENROUTER_REQUIRE_PARAMETERS"),
  OPENROUTER_REQUIRE_PARAMETERS_FOR_JSON: bool("OPENROUTER_REQUIRE_PARAMETERS_FOR_JSON", true),
  OPENROUTER_PROVIDER_ORDER: opt("OPENROUTER_PROVIDER_ORDER"),
  OPENROUTER_PROVIDER_ONLY: opt("OPENROUTER_PROVIDER_ONLY"),
  OPENROUTER_PROVIDER_IGNORE: opt("OPENROUTER_PROVIDER_IGNORE"),
  OPENROUTER_DATA_COLLECTION: opt("OPENROUTER_DATA_COLLECTION"),

  // Current Koyeb spreadsheet model names. One shared OPENROUTER_API_KEY is used for all models.
  OPENROUTER_ANTHROPIC_4_6: opt("OPENROUTER_ANTHROPIC_4_6"),
  OPENROUTER_GOOGLE_2_5_flashlite: opt("OPENROUTER_GOOGLE_2_5_flashlite"),
  OPENROUTER_CHATGPT_mini5_: opt("OPENROUTER_CHATGPT_mini5_"),
  OPENROUTER_DEEPSEEK_v4_pro: opt("OPENROUTER_DEEPSEEK_v4_pro"),
  OPENROUTER_DEEPSEEK_v4_flash: opt("OPENROUTER_DEEPSEEK_v4_flash"),

  // Legacy/provider-specific aliases remain optional for backwards compatibility.
  OPENROUTER_ANTHROPIC: opt("OPENROUTER_ANTHROPIC"),
  OPENROUTER_API_KEY_ANTHROPIC: opt("OPENROUTER_API_KEY_ANTHROPIC"),
  OPENROUTER_API_KEY_ART: opt("OPENROUTER_API_KEY_ART"),
  OPENROUTER_API_KEY_ART_BACKUP: opt("OPENROUTER_API_KEY_ART_BACKUP"),
  OPENROUTER_API_KEY_CHATGPT: opt("OPENROUTER_API_KEY_CHATGPT"),
  OPENROUTER_API_KEY_DEEPSEEK: opt("OPENROUTER_API_KEY_DEEPSEEK"),
  OPENROUTER_API_KEY_GOOGLE: opt("OPENROUTER_API_KEY_GOOGLE"),
  OPENROUTER_API_KEY_META: opt("OPENROUTER_API_KEY_META"),

  OPENROUTER_ART: opt("OPENROUTER_ART"),
  OPENROUTER_ART_BACKUP: opt("OPENROUTER_ART_BACKUP"),
  OPENROUTER_CHATGPT: opt("OPENROUTER_CHATGPT"),
  OPENROUTER_DEEPSEEK: opt("OPENROUTER_DEEPSEEK"),
  OPENROUTER_GOOGLE: opt("OPENROUTER_GOOGLE"),
  OPENROUTER_META: opt("OPENROUTER_META"),

  /* ---------------- RapidAPI ---------------- */
  RAPIDAPI_HOST: str("RAPIDAPI_HOST"),
  RAPIDAPI_KEY: str("RAPIDAPI_KEY"),

  /* ---------------- Outreach APIs ---------------- */
  API_SERP_KEY: opt("API_SERP_KEY"),
  API_OPENPAGERANK_KEY: opt("API_OPENPAGERANK_KEY"),
  API_URLSCAN_KEY: opt("API_URLSCAN_KEY"),
  API_PROSPEO_KEY: opt("API_PROSPEO_KEY"),
  API_HUNTER_KEY: opt("API_HUNTER_KEY"),
  API_APOLLO_KEY: opt("API_APOLLO_KEY"),
  API_ZERO_KEY: opt("API_ZERO_KEY"),

  /* ---------------- Outreach timing & policy ---------------- */
  SERP_RATE_DELAY_MS: num("SERP_RATE_DELAY_MS"),
  URLSCAN_DELAY_MS: num("URLSCAN_DELAY_MS"),
  APOLLO_DELAY_MS: num("APOLLO_DELAY_MS"),
  HUNTER_DELAY_MS: num("HUNTER_DELAY_MS"),

  RETRY_DELAY_MS: num("RETRY_DELAY_MS"),
  RETRY_BACKOFF_MULTIPLIER: num("RETRY_BACKOFF_MULTIPLIER"),

  SERP_RESULT_LIMIT: num("SERP_RESULT_LIMIT", 30),
  OUTREACH_BATCH_SIZE: num("OUTREACH_BATCH_SIZE"),
  OUTREACH_PROGRESS_KEY: opt("OUTREACH_PROGRESS_KEY", "outreach/progress.json"),
  OUTREACH_KEYWORDS: opt("OUTREACH_KEYWORDS"),
  OUTREACH_KEYWORDS_FILE: opt("OUTREACH_KEYWORDS_FILE"),
  ZEROBOUNCE_BATCH_SIZE: num("ZEROBOUNCE_BATCH_SIZE", 25),
  ZEROBOUNCE_TIMEOUT_MS: num("ZEROBOUNCE_TIMEOUT_MS", 30000),
  ZEROBOUNCE_DELAY_MS: num("ZEROBOUNCE_DELAY_MS"),

  OUTREACH_MIN_LEAD_SCORE: num("OUTREACH_MIN_LEAD_SCORE"),
  OUTREACH_MIN_EMAIL_SCORE: num("OUTREACH_MIN_EMAIL_SCORE"),

  /* ---------------- Feed / RSS ---------------- */
  FEED_URL: str("FEED_URL"),
  FEED_CUTOFF_HOURS: num("FEED_CUTOFF_HOURS", 48),
  FEED_FRESHNESS_HOURS: num("FEED_FRESHNESS_HOURS", 24),
  FEED_RETENTION_DAYS: num("FEED_RETENTION_DAYS", 60),
  FEED_FETCH_CONCURRENCY: num("FEED_FETCH_CONCURRENCY", 2),
  FEED_FETCH_TIMEOUT_MS: num("FEED_FETCH_TIMEOUT_MS", 15000),
  MAX_RSS_FEEDS_PER_RUN: num("MAX_RSS_FEEDS_PER_RUN", 5),
  MAX_URL_FEEDS_PER_RUN: num("MAX_URL_FEEDS_PER_RUN", 1),
  MAX_ITEMS_PER_FEED: num("MAX_ITEMS_PER_FEED", 5),
  RSS_OBJECT_KEY: opt("RSS_OBJECT_KEY", "feed.xml"),
  RSS_FEED_URL: opt("RSS_FEED_URL"),
  RSS_INCLUDE_WRAPPER_CTA: bool("RSS_INCLUDE_WRAPPER_CTA"),
  RSS_INIT_ON_BOOT: bool("RSS_INIT_ON_BOOT", false),
  RSS_INIT_REQUIRED_ON_BOOT: bool("RSS_INIT_REQUIRED_ON_BOOT", false),
  RSS_INIT_POST_START_TIMEOUT_MS: num("RSS_INIT_POST_START_TIMEOUT_MS", 120000),

  RSS_FEED_TITLE: opt("RSS_FEED_TITLE"),
  RSS_FEED_DESCRIPTION: opt("RSS_FEED_DESCRIPTION"),

  RSS_MIN_SOURCE_CHARS: num("RSS_MIN_SOURCE_CHARS", 220),
  RSS_TOPIC_GUARD_MIN_SHARED: num("RSS_TOPIC_GUARD_MIN_SHARED", 2),
  RSS_TOPIC_GUARD_MIN_OVERLAP: num("RSS_TOPIC_GUARD_MIN_OVERLAP", 0.12),

  /* ---------------- Podcast metadata ---------------- */
  PODCAST_TITLE: str("PODCAST_TITLE"),
  PODCAST_AUTHOR: str("PODCAST_AUTHOR"),
  PODCAST_DESCRIPTION: str("PODCAST_DESCRIPTION"),
  PODCAST_LINK: str("PODCAST_LINK"),
  PODCAST_LANGUAGE: (str("PODCAST_LANGUAGE", "en-gb") || "en-gb").toLowerCase().replace("en-uk", "en-gb"),
  PODCAST_EXPLICIT: bool("PODCAST_EXPLICIT", false),

  PODCAST_CATEGORY_1: opt("PODCAST_CATEGORY_1"),
  PODCAST_CATEGORY_2: opt("PODCAST_CATEGORY_2"),
  PODCAST_COPYRIGHT: opt("PODCAST_COPYRIGHT"),
  PODCAST_EPISODE_BASE_URL: opt("PODCAST_EPISODE_BASE_URL"),
  PODCAST_IMAGE_URL: opt("PODCAST_IMAGE_URL"),
  PODCAST_FALLBACK_IMAGE_URL: opt("PODCAST_FALLBACK_IMAGE_URL"),
  PODCAST_FALLBACK_EPISODE_IMAGE_URL: opt("PODCAST_FALLBACK_EPISODE_IMAGE_URL"),
  PODCAST_OWNER_NAME: opt("PODCAST_OWNER_NAME"),
  PODCAST_OWNER_EMAIL: opt("PODCAST_OWNER_EMAIL"),
  PODCASTINDEX_USER_AGENT: str("PODCASTINDEX_USER_AGENT"),

  PODCAST_INTRO_URL: opt("PODCAST_INTRO_URL"),
  PODCAST_OUTRO_URL: opt("PODCAST_OUTRO_URL"),

  PODCAST_FFMPEG_TIMEOUT_MS: num("PODCAST_FFMPEG_TIMEOUT_MS", 900000),
  PODCAST_FETCH_TIMEOUT_MS: num("PODCAST_FETCH_TIMEOUT_MS", 30000),
  PODCAST_ARTWORK_TIMEOUT_MS: num("PODCAST_ARTWORK_TIMEOUT_MS", 120000),
  PODCAST_TRANSCRIPT_HTML_BASE_URL: opt("PODCAST_TRANSCRIPT_HTML_BASE_URL"),
  PODCAST_TARGET_MINUTES: num("PODCAST_TARGET_MINUTES"),
  PODCAST_TARGET_MINS: num("PODCAST_TARGET_MINS"),
  PODCAST_DURATION_MINUTES: num("PODCAST_DURATION_MINUTES"),
  PODCAST_DURATION_MINS: num("PODCAST_DURATION_MINS"),
  PODCAST_MERGE_TMP_DIR: opt("PODCAST_MERGE_TMP_DIR"),
  PODCAST_EDIT_TMP_DIR: opt("PODCAST_EDIT_TMP_DIR"),
  PODCAST_MASTER_TMP_DIR: opt("PODCAST_MASTER_TMP_DIR"),
  MERGE_BATCH_SIZE: num("MERGE_BATCH_SIZE", 2),
  MERGE_CLEANUP_DELAY_MS: num("MERGE_CLEANUP_DELAY_MS", 120000),
  MERGE_DOWNLOAD_TIMEOUT_MS: num("MERGE_DOWNLOAD_TIMEOUT_MS", 30000),
  PODCAST_RSS_EP: opt("PODCAST_RSS_EP", "Yes"),
  PODCAST_RSS_ENABLED: opt("PODCAST_RSS_ENABLED", "yes"),

  API_KEY_PODCAST_INDEX: opt("API_KEY_PODCAST_INDEX"),
  API_SECRET_PODCAST_INDEX: opt("API_SECRET_PODCAST_INDEX"),
  PODCAST_LOCKED: opt("PODCAST_LOCKED"),
  PODCAST_LOCKED_OWNER_EMAIL: opt("PODCAST_LOCKED_OWNER_EMAIL"),
  PODCAST_GENERATOR: opt("PODCAST_GENERATOR"),
  PODCAST_GUID: opt("PODCAST_GUID"),

  /* ---------------- Polly / TTS ---------------- */
  POLLY_VOICE_ID: opt("POLLY_VOICE_ID", "Brian"),
  TTS_CONCURRENCY: num("TTS_CONCURRENCY", 1),
  MAX_POLLY_NATURAL_CHUNK_CHARS: num("MAX_POLLY_NATURAL_CHUNK_CHARS", 2800),
  MAX_SSML_CHUNK_BYTES: num("MAX_SSML_CHUNK_BYTES", 4200),
  MAX_CHUNK_RETRIES: num("MAX_CHUNK_RETRIES", 3),
  MAX_SUMMARY_CHARS: num("MAX_SUMMARY_CHARS", 2400),
  MIN_SUMMARY_CHARS: num("MIN_SUMMARY_CHARS", 900),

  /* ---------------- Blog / Social blog ---------------- */
  BLOG_PREFIX: opt("BLOG_PREFIX", "blog"),
  BLOG_WEEK_DAYS: num("BLOG_WEEK_DAYS", 7),
  BLOG_RSS_OBJECT_KEY: opt("BLOG_RSS_OBJECT_KEY", "feed.xml"),
  BLOG_RSS_FEED_URL: opt("BLOG_RSS_FEED_URL"),
  BLOG_RSS_TITLE: opt("BLOG_RSS_TITLE"),
  BLOG_RSS_DESCRIPTION: opt("BLOG_RSS_DESCRIPTION"),
  BLOG_RSS_IMAGE_URL: opt("BLOG_RSS_IMAGE_URL"),
  BLOG_FALLBACK_IMAGE_URL: opt("BLOG_FALLBACK_IMAGE_URL"),
  BLOG_WEEKLY_QA_ENABLED: bool("BLOG_WEEKLY_QA_ENABLED", true),
  BLOG_ARTWORK_BUCKET_ALIAS: opt("BLOG_ARTWORK_BUCKET_ALIAS"),
  BLOG_SOCIAL_PREFIX: opt("BLOG_SOCIAL_PREFIX", "social-media-blog"),
  BLOG_SOCIAL_PUBLIC_BASE_URL: opt("BLOG_SOCIAL_PUBLIC_BASE_URL"),
  BLOG_SOCIAL_PUBLIC_POSTS_BASE_URL: opt("BLOG_SOCIAL_PUBLIC_POSTS_BASE_URL"),
  BLOG_SOCIAL_RSS_OBJECT_KEY: opt("BLOG_SOCIAL_RSS_OBJECT_KEY", "social-media-blog/feed.xml"),
  BLOG_SOCIAL_RSS_TITLE: opt("BLOG_SOCIAL_RSS_TITLE"),
  BLOG_SOCIAL_RSS_DESCRIPTION: opt("BLOG_SOCIAL_RSS_DESCRIPTION"),
  BLOG_SOCIAL_FALLBACK_IMAGE_URL: opt("BLOG_SOCIAL_FALLBACK_IMAGE_URL"),
  BLOG_SOCIAL_QA_ENABLED: bool("BLOG_SOCIAL_QA_ENABLED", true),

  /* ---------------- R2 ---------------- */
  R2_ENDPOINT: opt("R2_ENDPOINT"),
  R2_REGION: opt("R2_REGION", "auto"),
  R2_ACCESS_KEY_ID: opt("R2_ACCESS_KEY_ID"),
  R2_SECRET_ACCESS_KEY: opt("R2_SECRET_ACCESS_KEY"),

  R2_BUCKET_PODCAST: opt("R2_BUCKET_PODCAST"),
  R2_BUCKET_RAW_TEXT: opt("R2_BUCKET_RAW_TEXT"),
  R2_BUCKET_CHUNKS: opt("R2_BUCKET_CHUNKS"), // raw TTS audio
  R2_BUCKET_RAW: opt("R2_BUCKET_RAW"),       // alias → same bucket
  R2_BUCKET_META: opt("R2_BUCKET_META"),
  R2_BUCKET_META_SYSTEM: opt("R2_BUCKET_META_SYSTEM"),
  R2_BUCKET_MERGED: opt("R2_BUCKET_MERGED"),
  R2_BUCKET_EDITED_AUDIO: opt("R2_BUCKET_EDITED_AUDIO"),
  R2_BUCKET_TRANSCRIPTS: opt("R2_BUCKET_TRANSCRIPTS"),
  R2_BUCKET_RSS_FEEDS: opt("R2_BUCKET_RSS_FEEDS"),
  R2_BUCKET_PODCAST_RSS_FEEDS: opt("R2_BUCKET_PODCAST_RSS_FEEDS"),
  R2_BUCKET_ART: opt("R2_BUCKET_ART"),
  R2_BUCKET_BLOG: opt("R2_BUCKET_BLOG"),
  R2_BUCKET_BLOG_IMAGES: opt("R2_BUCKET_BLOG_IMAGES"),
  R2_BUCKET_BLOG_RSS: opt("R2_BUCKET_BLOG_RSS"),
  R2_BUCKET_BRAND_ASSETS: opt("R2_BUCKET_BRAND_ASSETS"),
  R2_BUCKET_AUDITS: opt("R2_BUCKET_AUDITS"),
  R2_BUCKET_METASYSTEM: opt("R2_BUCKET_METASYSTEM"),
  R2_META_BUCKET: opt("R2_META_BUCKET"),
  R2_META_SYSTEM_BUCKET: opt("R2_META_SYSTEM_BUCKET"),
  R2_REQUEST_TIMEOUT_MS: num("R2_REQUEST_TIMEOUT_MS", 15000),

  R2_PUBLIC_BASE_URL_PODCAST: opt("R2_PUBLIC_BASE_URL_PODCAST"),
  R2_PUBLIC_BASE_URL_RAW_TEXT: opt("R2_PUBLIC_BASE_URL_RAW_TEXT"),
  R2_PUBLIC_BASE_URL_META: opt("R2_PUBLIC_BASE_URL_META"),
  R2_PUBLIC_BASE_URL_MERGE: opt("R2_PUBLIC_BASE_URL_MERGE"),
  R2_PUBLIC_BASE_URL_RSS: opt("R2_PUBLIC_BASE_URL_RSS"),
  R2_PUBLIC_BASE_URL_ART: opt("R2_PUBLIC_BASE_URL_ART"),
  R2_PUBLIC_BASE_URL_CHUNKS: opt("R2_PUBLIC_BASE_URL_CHUNKS"),
  R2_PUBLIC_BASE_URL_EDITED_AUDIO: opt("R2_PUBLIC_BASE_URL_EDITED_AUDIO"),
  R2_PUBLIC_BASE_URL_PODCAST_RSS: opt("R2_PUBLIC_BASE_URL_PODCAST_RSS"),
  R2_PUBLIC_BASE_URL_TRANSCRIPT: opt("R2_PUBLIC_BASE_URL_TRANSCRIPT"),
  R2_PUBLIC_BASE_URL_TRANSCRIPT_HTML: opt("R2_PUBLIC_BASE_URL_TRANSCRIPT_HTML"),
  R2_PUBLIC_BASE_URL_META_SYSTEM: opt("R2_PUBLIC_BASE_URL_META_SYSTEM"),
  R2_PUBLIC_BASE_URL_BLOG: opt("R2_PUBLIC_BASE_URL_BLOG"),
  R2_PUBLIC_BASE_URL_BLOG_IMAGES: opt("R2_PUBLIC_BASE_URL_BLOG_IMAGES"),
  R2_PUBLIC_BASE_URL_BLOG_RSS: opt("R2_PUBLIC_BASE_URL_BLOG_RSS"),
  R2_PUBLIC_BASE_URL_BRAND_ASSETS: opt("R2_PUBLIC_BASE_URL_BRAND_ASSETS"),
  R2_PUBLIC_BASE_URL_AUDITS: opt("R2_PUBLIC_BASE_URL_AUDITS"),
  R2_PUBLIC_BASE_URL_RSS_FEEDS: opt("R2_PUBLIC_BASE_URL_RSS_FEEDS"),

  /* ---------------- Google Sheets ---------------- */
  GOOGLE_CLIENT_EMAIL: str("GOOGLE_CLIENT_EMAIL"),
  GOOGLE_PRIVATE_KEY: opt("GOOGLE_PRIVATE_KEY"),
  GOOGLE_SHEET_ID: str("GOOGLE_SHEET_ID"),

  /* ---------------- Funding / iTunes ---------------- */
  PODCAST_RSS_FEED_URL: firstDefined("PODCAST_RSS_FEED_URL"),
  PODCAST_FUNDING_TEXT: firstDefined("PODCAST_FUNDING_TEXT", "funding_text"),
  PODCAST_FUNDING_URL: firstDefined("PODCAST_FUNDING_URL", "funding_url"),
  PODCAST_ITUNES_KEYWORDS: firstDefined("PODCAST_ITUNES_KEYWORDS", "itunes_keywords"),
  PODCAST_ITUNES_TYPE: firstDefined("PODCAST_ITUNES_TYPE", "itunes_type"),
  funding_text: firstDefined("funding_text", "PODCAST_FUNDING_TEXT"),
  funding_url: firstDefined("funding_url", "PODCAST_FUNDING_URL"),
  itunes_keywords: firstDefined("itunes_keywords", "PODCAST_ITUNES_KEYWORDS"),
  itunes_type: firstDefined("itunes_type", "PODCAST_ITUNES_TYPE"),


  /* ---------------- Blotato ---------------- */
  Blotato_API_key: opt("Blotato_API_key"),
  BLOTATO_API_KEY: opt("BLOTATO_API_KEY"),
  BLOTATO_API_BASE: opt("BLOTATO_API_BASE", "https://backend.blotato.com/v2"),
  BLOTATO_TIMEOUT_MS: num("BLOTATO_TIMEOUT_MS", 30000),
  BLOTATO_NEWS_SHORT_MAX_TOKENS: num("BLOTATO_NEWS_SHORT_MAX_TOKENS", 2200),
  BLOTATO_NEWS_DURATION_SECONDS: num("BLOTATO_NEWS_DURATION_SECONDS", 45),
  BLOTATO_NEWS_THEME: opt("BLOTATO_NEWS_THEME"),
  BLOTATO_NEWS_AUDIENCE: opt("BLOTATO_NEWS_AUDIENCE"),
  BLOTATO_NEWS_CTA: opt("BLOTATO_NEWS_CTA"),
  BLOTATO_NEWS_VOICE_NAME: opt("BLOTATO_NEWS_VOICE_NAME"),
  BLOTATO_NEWS_HIGHLIGHT_COLOR: opt("BLOTATO_NEWS_HIGHLIGHT_COLOR"),
  BLOTATO_NEWS_CAPTION_POSITION: opt("BLOTATO_NEWS_CAPTION_POSITION"),
  BLOTATO_NEWS_TRANSITION: opt("BLOTATO_NEWS_TRANSITION"),
  BLOTATO_NEWS_ASPECT_RATIO: opt("BLOTATO_NEWS_ASPECT_RATIO"),
  BLOTATO_INLINE_PUBLISH_JOBS: bool("BLOTATO_INLINE_PUBLISH_JOBS", false),
  BLOTATO_NEWS_TEMPLATE_ID: opt("BLOTATO_NEWS_TEMPLATE_ID"),
  BLOTATO_NEWS_RSS_URL: opt("BLOTATO_NEWS_RSS_URL"),
  BLOTATO_RSS_FEED_URL: opt("BLOTATO_RSS_FEED_URL"),
  BLOTATO_RSS_FETCH_TIMEOUT_MS: num("BLOTATO_RSS_FETCH_TIMEOUT_MS"),
  BLOTATO_RSS_PREFER_R2: bool("BLOTATO_RSS_PREFER_R2", true),
  BLOTATO_RSS_BUCKET_ALIAS: opt("BLOTATO_RSS_BUCKET_ALIAS", "rss"),
  BLOTATO_RSS_JSON_KEY: opt("BLOTATO_RSS_JSON_KEY", "feed.json"),
  BLOTATO_RSS_PICK_MODE: opt("BLOTATO_RSS_PICK_MODE", "latest"),
  BLOTATO_DEFAULT_CHANNELS: opt("BLOTATO_DEFAULT_CHANNELS", "instagram,youtube,tiktok,facebook"),
  BLOTATO_INSTAGRAM_ACCOUNT_ID: opt("BLOTATO_INSTAGRAM_ACCOUNT_ID"),
  BLOTATO_YOUTUBE_ACCOUNT_ID: opt("BLOTATO_YOUTUBE_ACCOUNT_ID"),
  BLOTATO_TIKTOK_ACCOUNT_ID: opt("BLOTATO_TIKTOK_ACCOUNT_ID"),
  BLOTATO_FACEBOOK_ACCOUNT_ID: opt("BLOTATO_FACEBOOK_ACCOUNT_ID"),
  BLOTATO_FACEBOOK_PAGE_ID: opt("BLOTATO_FACEBOOK_PAGE_ID"),
  BLOTATO_FACEBOOK_SUBACCOUNT_ID: opt("BLOTATO_FACEBOOK_SUBACCOUNT_ID"),
  BLOTATO_YOUTUBE_PRIVACY_STATUS: opt("BLOTATO_YOUTUBE_PRIVACY_STATUS", "public"),
  BLOTATO_YOUTUBE_NOTIFY_SUBSCRIBERS: bool("BLOTATO_YOUTUBE_NOTIFY_SUBSCRIBERS", false),
  BLOTATO_INSTAGRAM_SHARE_TO_FEED: bool("BLOTATO_INSTAGRAM_SHARE_TO_FEED", true),
  BLOTATO_VIDEO_POLL_ATTEMPTS: num("BLOTATO_VIDEO_POLL_ATTEMPTS", 90),
  BLOTATO_VIDEO_POLL_INTERVAL_MS: num("BLOTATO_VIDEO_POLL_INTERVAL_MS", 3000),
  BLOTATO_POST_POLL_ATTEMPTS: num("BLOTATO_POST_POLL_ATTEMPTS", 60),
  BLOTATO_POST_POLL_INTERVAL_MS: num("BLOTATO_POST_POLL_INTERVAL_MS", 3000),

  /* ---------------- OneUp social scheduler ---------------- */
  ONEUP_API_KEY: opt("ONEUP_API_KEY"),
  ONEUP_API_BASE: opt("ONEUP_API_BASE", "https://www.oneupapp.io/api"),
  ONEUP_TIMEZONE: opt("ONEUP_TIMEZONE", "Europe/London"),
  ONEUP_CATEGORY_NAME_GENERAL: opt("ONEUP_CATEGORY_NAME_GENERAL", "General"),
  ONEUP_CATEGORY_NAME_EBOOKS: opt("ONEUP_CATEGORY_NAME_EBOOKS", "Ebooks"),
  ONEUP_SOCIAL_NETWORK_ID: opt("ONEUP_SOCIAL_NETWORK_ID", "ALL"),
  ONEUP_DEFAULT_DRY_RUN: bool("ONEUP_DEFAULT_DRY_RUN", false),
  ONEUP_RSS_LOOKBACK_DAYS: num("ONEUP_RSS_LOOKBACK_DAYS", 7),
  ONEUP_QUEUE_GUARD_LOOKBACK_PAGES: num("ONEUP_QUEUE_GUARD_LOOKBACK_PAGES", 2),
  ONEUP_MONDAY_TIME: opt("ONEUP_MONDAY_TIME", "14:00"),
  ONEUP_TUESDAY_TIME: opt("ONEUP_TUESDAY_TIME", "13:00"),
  ONEUP_WEDNESDAY_TIME: opt("ONEUP_WEDNESDAY_TIME", "12:20"),
  ONEUP_THURSDAY_TIME: opt("ONEUP_THURSDAY_TIME", "12:20"),
  ONEUP_FRIDAY_TIME: opt("ONEUP_FRIDAY_TIME", "11:20"),
  ONEUP_SATURDAY_TIME: opt("ONEUP_SATURDAY_TIME", "10:30"),
  ONEUP_SUNDAY_TIME: opt("ONEUP_SUNDAY_TIME", "18:00"),
  ONEUP_QUIZ_QUESTION_TIME: opt("ONEUP_QUIZ_QUESTION_TIME", "12:00"),
  ONEUP_QUIZ_ANSWER_TIME: opt("ONEUP_QUIZ_ANSWER_TIME", "12:00"),
  ONEUP_EBOOK_TUESDAY_TIME: opt("ONEUP_EBOOK_TUESDAY_TIME"),
  ONEUP_EBOOK_THURSDAY_TIME: opt("ONEUP_EBOOK_THURSDAY_TIME"),
  ONEUP_EBOOK_SATURDAY_TIME: opt("ONEUP_EBOOK_SATURDAY_TIME"),
  ONEUP_DAILY_MAX_TOKENS: num("ONEUP_DAILY_MAX_TOKENS", 1400),
  ONEUP_QUIZ_MAX_TOKENS: num("ONEUP_QUIZ_MAX_TOKENS", 2200),
  ONEUP_EBOOK_MAX_TOKENS: num("ONEUP_EBOOK_MAX_TOKENS", 1600),
  ONEUP_SLOT_PENDING_TTL_MS: num("ONEUP_SLOT_PENDING_TTL_MS", 7200000),
  ONEUP_SLOT_COMPLETED_TTL_MS: num("ONEUP_SLOT_COMPLETED_TTL_MS", 7776000000),
  ONEUP_EBOOK_CATALOGUE_PATH: opt("ONEUP_EBOOK_CATALOGUE_PATH"),
  ONEUP_MONDAY_IMAGE_URL: opt("ONEUP_MONDAY_IMAGE_URL"),
  ONEUP_TUESDAY_IMAGE_URL: opt("ONEUP_TUESDAY_IMAGE_URL"),
  ONEUP_WEDNESDAY_IMAGE_URL: opt("ONEUP_WEDNESDAY_IMAGE_URL"),
  ONEUP_THURSDAY_IMAGE_URL: opt("ONEUP_THURSDAY_IMAGE_URL"),
  ONEUP_FRIDAY_IMAGE_URL: opt("ONEUP_FRIDAY_IMAGE_URL"),
  ONEUP_SATURDAY_IMAGE_URL: opt("ONEUP_SATURDAY_IMAGE_URL"),
  ONEUP_SUNDAY_IMAGE_URL: opt("ONEUP_SUNDAY_IMAGE_URL"),
  ONEUP_QUIZ_IMAGE_URL: opt("ONEUP_QUIZ_IMAGE_URL"),
  ONEUP_QUIZ_ANSWER_IMAGE_URL: opt("ONEUP_QUIZ_ANSWER_IMAGE_URL"),


  /* ---------------- AWS ---------------- */
  AWS_REGION: opt("AWS_REGION", "eu-west-2"),
  AWS_ACCESS_KEY_ID: opt("AWS_ACCESS_KEY_ID"),
  AWS_SECRET_ACCESS_KEY: opt("AWS_SECRET_ACCESS_KEY"),
};
