#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.join(ROOT, "docs", "ENVIRONMENT_REFERENCE.md");
const SOURCE_ROOTS = ["."];
const TEMPLATE_FILES = [".env.example", "env.template"];
const ENV_PATTERN = /process\.env\.([A-Z][A-Z0-9_]*)|process\.env\[['"]([A-Z][A-Z0-9_]*)['"]\]/g;
const ASSIGNMENT_PATTERN = /^\s*(?:export\s+)?([A-Z][A-Z0-9_]*)\s*=/;

function walk(entry) {
  const absolute = path.join(ROOT, entry);
  if (!fs.existsSync(absolute)) return [];
  const stat = fs.statSync(absolute);
  if (stat.isFile()) return absolute.endsWith(".js") ? [absolute] : [];
  const files = [];
  for (const item of fs.readdirSync(absolute, { withFileTypes: true })) {
    if (["node_modules", ".git", ".github", "dist", "coverage", "test", "tests"].includes(item.name)) continue;
    const child = path.join(absolute, item.name);
    if (item.isDirectory()) files.push(...walk(path.relative(ROOT, child)));
    else if (item.isFile() && item.name.endsWith(".js") && !item.name.endsWith(".test.js")) files.push(child);
  }
  return files;
}

function templateKeys() {
  const keys = new Set();
  for (const name of TEMPLATE_FILES) {
    const file = path.join(ROOT, name);
    if (!fs.existsSync(file)) continue;
    for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = line.match(ASSIGNMENT_PATTERN);
      if (match) keys.add(match[1]);
    }
  }
  return keys;
}

function collect() {
  const refs = new Map();
  const files = SOURCE_ROOTS.flatMap(walk);
  for (const file of files) {
    const rel = path.relative(ROOT, file).replaceAll(path.sep, "/");
    const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
    lines.forEach((line, index) => {
      ENV_PATTERN.lastIndex = 0;
      let match;
      while ((match = ENV_PATTERN.exec(line))) {
        const name = match[1] || match[2];
        if (!refs.has(name)) refs.set(name, []);
        refs.get(name).push(`${rel}:${index + 1}`);
      }
    });
  }
  return refs;
}

function render() {
  const refs = collect();
  const templated = templateKeys();
  const names = [...refs.keys()].sort();
  const inTemplates = names.filter((name) => templated.has(name)).length;
  const generated = [];
  generated.push("# AIMS Environment Variable Reference");
  generated.push("");
  generated.push("> Generated from production JavaScript by `npm run env:reference:write`. Do not edit this file by hand.");
  generated.push("");
  generated.push("This inventory makes the runtime configuration contract auditable without duplicating secret values. `.env.example` and `env.template` remain the curated operator templates; this file records every production `process.env` dependency and its source locations.");
  generated.push("");
  generated.push(`- Runtime variables referenced in production code: **${names.length}**`);
  generated.push(`- Present in curated templates: **${inTemplates}**`);
  generated.push(`- Not present in curated templates: **${names.length - inTemplates}**`);
  generated.push("");
  generated.push("| Variable | Curated template | Production references |");
  generated.push("| --- | --- | --- |");
  for (const name of names) {
    const locations = [...new Set(refs.get(name))];
    const display = locations.length <= 6 ? locations.join("<br>") : `${locations.slice(0, 6).join("<br>")}<br>+${locations.length - 6} more`;
    generated.push(`| \`${name}\` | ${templated.has(name) ? "Yes" : "No"} | ${display} |`);
  }
  generated.push("");
  generated.push("## Governance");
  generated.push("");
  generated.push("CI runs `npm run env:reference:check`. Any new, removed or renamed production environment dependency changes this generated file and fails verification until the reference is deliberately regenerated and reviewed. Secrets must never be written into this document.");
  generated.push("");
  return generated.join("\n") + "\n";
}

const expected = render();
const mode = process.argv[2] || "--check";
if (mode === "--write") {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, expected);
  console.log(`Wrote ${path.relative(ROOT, OUTPUT)}.`);
  process.exit(0);
}
if (mode !== "--check") {
  console.error("Usage: node scripts/envReference.js [--check|--write]");
  process.exit(2);
}
if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, "utf8") !== expected) {
  console.error("Environment reference is stale. Run `npm run env:reference:write` and commit the result.");
  process.exit(1);
}
console.log("Environment reference is current.");
