/**
 * feedGenerator.js
 * Builds and uploads a W3C-valid RSS 2.0 feed using rewritten articles.
 * Merges new items with existing feed items, respecting FEED_RETENTION_DAYS.
 */

import crypto from "crypto";
import { XMLBuilder } from "fast-xml-parser";
import { r2Put, r2Get } from "../../shared/utils/r2-client.js";
import { info, error, debug } from "../../../logger.js";
import { RSS_PROMPTS } from "./rss-prompts.js";

const FEED_RETENTION_DAYS = Number(process.env.FEED_RETENTION_DAYS) || 7; // default 7 days
const INCLUDE_WRAPPER_CTA = /^(1|true|yes|on)$/i.test(
  String(process.env.RSS_INCLUDE_WRAPPER_CTA || "")
);

export async function generateFeed(bucket, rewrittenItems) {
  try {
    if (!Array.isArray(rewrittenItems) || rewrittenItems.length === 0) {
      debug("rss-feed-creator.generateFeed.skip", { reason: "no items" });
      return;
    }

    const now = new Date();
    const buildDate = now.toUTCString();
    const retentionCutoff = new Date(now.getTime() - FEED_RETENTION_DAYS * 24 * 60 * 60 * 1000);

    const channelTitle =
      process.env.RSS_FEED_TITLE?.trim() || "Turing's Torch: AI Weekly";
    const channelLink =
      process.env.APP_URL?.trim() ||
      process.env.PODCAST_LINK?.trim() ||
      "https://jonathan-harris.online";
    const feedSelfLink =
      process.env.R2_PUBLIC_BASE_URL_RSS?.trim()
        ? `${process.env.R2_PUBLIC_BASE_URL_RSS.trim()}/feed.xml`
        : `${channelLink.replace(/\/$/, "")}/feed.xml`;
    const channelDesc =
      process.env.RSS_FEED_DESCRIPTION?.trim() ||
      "AI insights and rewritten articles generated by Jonathan Harris's AI Podcast Suite.";

    // Load existing feed items from R2
    const existingItems = await loadExistingFeedItems(bucket);

    // Normalize new items (HARD: only publish items with a valid rewritten summary)
    const newItems = rewrittenItems
      .filter((x) => x && typeof x === "object")
      .map((item) => normalizeItem(item, channelLink, now));

    // Merge existing and new items, deduplicate by link or guid
    const mergedItems = mergeAndDeduplicateItems(existingItems, newItems);

    const publishableItems = mergedItems.filter((item) => {
      const issues = getPublicationIssues(item);
      if (issues.length) {
        debug("rss-feed-creator.generateFeed.itemRejected", {
          title: item?.title,
          link: item?.link,
          issues: issues.slice(0, 6),
        });
        return false;
      }
      return true;
    });

    // Filter by retention period
    const validItems = publishableItems.filter((item) =>
      isWithinRetention(item.pubDate, retentionCutoff)
    );

    // Sort by pubDate descending (newest first)
    validItems.sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));

    const totalBeforeRetention = publishableItems.length;
    const discardedCount = totalBeforeRetention - validItems.length;

    debug("rss-feed-creator.generateFeed.retention", {
      retentionDays: FEED_RETENTION_DAYS,
      cutoff: retentionCutoff.toISOString(),
      beforeRetention: publishableItems.length,
      afterRetention: validItems.length,
      discarded: discardedCount,
    });

    if (validItems.length === 0) {
      debug("rss-feed-creator.generateFeed.skip", {
        reason: "no items within retention period",
        retentionDays: FEED_RETENTION_DAYS,
        discarded: discardedCount,
      });
      return;
    }

    const feedState = {
      rss: {
        "@_version": "2.0",
        "@_xmlns:atom": "http://www.w3.org/2005/Atom",
        channel: {
          title: channelTitle,
          link: channelLink,
          description: channelDesc,
          language: "en-gb",
          lastBuildDate: buildDate,
          pubDate: buildDate,
          generator: "AI Podcast Suite - RSS Feed Creator",
          "atom:link": {
            "@_href": feedSelfLink,
            "@_rel": "self",
            "@_type": "application/rss+xml",
          },
          item: validItems.map((it) => ({
            title: it.title || "Untitled Article",
            link: it.link,
            guid: { "@_isPermaLink": "false", "#text": it.guid },
            pubDate: it.pubDate,
            description: {
              __cdata: buildDescriptionHtml(it.title, it.rewritten, it.link),
            },
          })),
        },
      },
    };

    const feedObj = buildXmlFeedObject(feedState);

    const builder = new XMLBuilder({
      format: true,
      ignoreAttributes: false,
      suppressEmptyNode: true,
      cdataPropName: "__cdata",
    });

    const xmlString =
      '<?xml version="1.0" encoding="UTF-8"?>\n' + builder.build(feedObj);
    const jsonString = JSON.stringify(feedState, null, 2);

    await r2Put(bucket, "feed.xml", xmlString, "application/rss+xml");
    await r2Put(bucket, "feed.json", jsonString, "application/json");

    info("📝 rss-feed-creator.generateFeed.success");
    debug("📝 rss-feed-creator.generateFeed.success", {
      bucket,
      existingItems: existingItems.length,
      newItems: newItems.length,
      totalItems: validItems.length,
      discarded: discardedCount,
      retentionDays: FEED_RETENTION_DAYS,
      size: xmlString.length,
    });
  } catch (err) {
    error("rss-feed-creator.generateFeed.fail", {
      bucket,
      message: err?.message,
      stack: err?.stack,
    });
    throw err;
  }
}

// ──────────────────────────────
// Helpers
// ──────────────────────────────

async function loadExistingFeedItems(bucket) {
  try {
    const jsonContent = await r2Get(bucket, "feed.json");
    if (!jsonContent) return [];

    const feedData = JSON.parse(jsonContent);
    const items = feedData?.rss?.channel?.item || [];

    // Convert back to our internal format
    return (Array.isArray(items) ? items : [items]).map((item) => ({
      title: normalizeCanonicalTitle(item.title || "Untitled Article"),
      link: item.link || "",
      pubDate: item.pubDate || new Date().toUTCString(),
      guid: item.guid?.["#text"] || item.guid || "",
      rewritten: RSS_PROMPTS.clampSummaryToWindow(
        extractTextFromCDATA(item.description?.__cdata || ""),
        RSS_PROMPTS.MIN_SUMMARY_CHARS,
        RSS_PROMPTS.MAX_SUMMARY_CHARS
      ),
    }));
  } catch (err) {
    info("rss-feed-creator.loadExisting.fail", {
      bucket,
      reason: err.message,
      note: "Starting with empty feed",
    });
    return [];
  }
}

function extractTextFromCDATA(cdataHtml) {
  const html = String(cdataHtml || "");
  const withoutTitle = html.replace(/^\s*<strong>[\s\S]*?<\/strong>/i, "").trim();
  const withoutLegacyCta = withoutTitle.replace(
    /<a\b[^>]*>\s*Read on Jonathan-Harris RSS Feed\s*<\/a>/gi,
    ""
  );

  return htmlToPlainText(withoutLegacyCta);
}

function mergeAndDeduplicateItems(existingItems, newItems) {
  const itemMap = new Map();

  // Add existing items first
  for (const item of existingItems) {
    const key = item.link || item.guid;
    if (key) {
      itemMap.set(key, item);
    }
  }

  // Add/overwrite with new items (new items take precedence)
  for (const item of newItems) {
    const key = item.link || item.guid;
    if (key) {
      itemMap.set(key, item);
    }
  }

  return Array.from(itemMap.values());
}

function isWithinRetention(pubDateStr, cutoffDate) {
  try {
    const itemDate = new Date(pubDateStr);
    if (isNaN(itemDate.getTime())) return false;

    // Keep items that are newer than the cutoff and not in the future
    return itemDate >= cutoffDate && itemDate <= new Date();
  } catch {
    return false;
  }
}

function normalizeItem(item, fallbackLink, now) {
  const title = normalizeCanonicalTitle(item?.shortTitle || item?.title || "Untitled Article");
  const link = normalizeUrl(item?.shortUrl || item?.link || fallbackLink);

  // Parse pubDate and keep as ISO string for easier comparison
  let pubDate;
  try {
    const d = item?.pubDate ? new Date(item.pubDate) : now;
    pubDate = isNaN(d.getTime()) ? now.toUTCString() : d.toUTCString();
  } catch {
    pubDate = now.toUTCString();
  }

  // Use existing GUID if available, otherwise generate new one
  let guid = item?.guid || item?.shortGuid;
  if (!guid) {
    const randomId = parseInt(crypto.randomBytes(6).toString("hex"), 16)
      .toString(36)
      .slice(0, 12);
    guid = `ai-news-${randomId}`;
  }

  // HARD: publish rewritten only (never fall back to source summary).
  // The RSS item title already carries the headline, so strip accidental
  // title echoes from the opening of the summary before publication.
  const titleSafeSummary = RSS_PROMPTS.stripLeadingTitleFromSummary(title, item?.rewritten || "");
  const rewritten = RSS_PROMPTS.clampSummaryToWindow(
    titleSafeSummary,
    RSS_PROMPTS.MIN_SUMMARY_CHARS,
    RSS_PROMPTS.MAX_SUMMARY_CHARS
  );

  return { title, link, pubDate, guid, rewritten };
}

function buildDescriptionHtml(title, rewrittenText, link) {
  const safeTitle = escapeHtml(normalizeCanonicalTitle(title));
  const body = renderParagraphHtml(
    RSS_PROMPTS.clampSummaryToPreferredBrief(
      RSS_PROMPTS.stripLeadingTitleFromSummary(safeTitle, rewrittenText),
      RSS_PROMPTS.PREFERRED_SUMMARY_WORDS
    )
  );

  if (!body) {
    return safeTitle ? `<p>${safeTitle}</p>` : "";
  }

  if (!INCLUDE_WRAPPER_CTA || !link) {
    return body;
  }

  const safeLink = escapeHtml(link);
  const anchor = `<p><a href="${safeLink}">Read on Jonathan-Harris RSS Feed</a></p>`;
  return `${body}${anchor}`;
}

function getPublicationIssues(item) {
  const issues = [];
  const title = normalizeCanonicalTitle(item?.title || "");
  const rewritten = RSS_PROMPTS.normalizeSummaryText(item?.rewritten || "");

  const titleValidation = RSS_PROMPTS.validateTitleBrand(title);
  if (!titleValidation.valid) {
    issues.push(...titleValidation.errors);
  }

  if (!rewritten) {
    issues.push("Summary is empty");
  }
  if (/^\s*REWRITE_ABORTED\s*$/i.test(rewritten)) {
    issues.push('Summary is sentinel value "REWRITE_ABORTED"');
  }
  if (rewritten.startsWith("⚠️")) {
    issues.push("Summary begins with warning sentinel");
  }
  if (/<[^>]+>/.test(rewritten)) {
    issues.push("Summary contains raw HTML markup");
  }
  if (RSS_PROMPTS.hasMetadataLeak(rewritten)) {
    issues.push(...RSS_PROMPTS.findMetadataLeaks(rewritten));
  }

  const bannedPhrases = RSS_PROMPTS.findBannedSummaryPhrases(rewritten);
  if (bannedPhrases.length) {
    issues.push(`Summary contains banned filler: ${bannedPhrases.slice(0, 5).join(", ")}`);
  }

  const summaryStyle = RSS_PROMPTS.findRssSummaryStyleIssues(title, rewritten);
  issues.push(...summaryStyle.errors);

  // Guard against ultra-short junk
  if (rewritten && rewritten.length < 120) {
    issues.push(`Summary too short for publication (${rewritten.length} chars)`);
  }

  if (rewritten && rewritten.length > RSS_PROMPTS.MAX_SUMMARY_CHARS) {
    issues.push(
      `Summary too long for publication (${rewritten.length} chars, max ${RSS_PROMPTS.MAX_SUMMARY_CHARS})`
    );
  }

  return Array.from(new Set(issues));
}

function isPublishable(item) {
  return getPublicationIssues(item).length === 0;
}

function normalizeUrl(url = "") {
  try {
    const u = new URL(url);
    // Normalize host to lowercase to avoid mixed-case hosts
    u.host = u.host.toLowerCase();
    // Ensure https scheme
    if (u.protocol !== "https:") u.protocol = "https:";
    return withRssLinksIndexHtml(u).href;
  } catch {
    return "";
  }
}

function withRssLinksIndexHtml(url) {
  const match = url.pathname.match(/^\/rss-links\/([A-Za-z0-9]{4,32})\/?$/);
  if (match) {
    url.pathname = `/rss-links/${match[1]}/index.html`;
  }
  return url;
}

function renderParagraphHtml(text = "") {
  const normalized = RSS_PROMPTS.normalizeSummaryText(text);
  if (!normalized) return "";

  return normalized
    .split(/\n\n+/)
    .filter(Boolean)
    .map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`)
    .join("");
}

function normalizeCanonicalTitle(title = "") {
  return RSS_PROMPTS.normalizePlainText(decodeHtmlEntitiesFully(title));
}

function htmlToPlainText(html = "") {
  const withParagraphs = String(html || "")
    .replace(/<\/p>\s*<p[^>]*>/gi, "\n\n")
    .replace(/<p[^>]*>/gi, "")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<br\s*\/?>\s*<br\s*\/?>/gi, "\n\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]*>/g, " ");

  return RSS_PROMPTS.normalizeSummaryText(decodeHtmlEntitiesFully(withParagraphs));
}

function decodeHtmlEntitiesFully(str = "") {
  let current = String(str || "");

  for (let i = 0; i < 4; i++) {
    const next = decodeHtmlEntitiesOnce(current);
    if (next === current) break;
    current = next;
  }

  return current;
}

function decodeHtmlEntitiesOnce(str = "") {
  return String(str)
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&apos;/gi, "'")
    .replace(/&#39;/gi, "'")
    .replace(/&#x27;/gi, "'");
}

function buildXmlFeedObject(feedState) {
  const channel = feedState?.rss?.channel || {};
  const items = channel?.item || [];
  const itemList = Array.isArray(items) ? items : [items];

  return {
    rss: {
      "@_version": "2.0",
      "@_xmlns:atom": "http://www.w3.org/2005/Atom",
      channel: {
        title: channel.title || "",
        link: channel.link || "",
        description: channel.description || "",
        language: channel.language || "en-gb",
        lastBuildDate: channel.lastBuildDate,
        pubDate: channel.pubDate,
        generator: channel.generator,
        "atom:link": channel["atom:link"],
        item: itemList.map((item) => ({
          title: item.title || "Untitled Article",
          link: item.link,
          guid: item.guid,
          pubDate: item.pubDate,
          description: item.description,
        })),
      },
    },
  };
}

function escapeHtml(str = "") {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export const __testing = {
  buildXmlFeedObject,
  getPublicationIssues,
  normalizeItem,
  extractTextFromCDATA,
};
